In [1]:
name = input("Enter your name: ")
age = input("Enter your age: ")
print(f"Hello {name}, you are {age} years old!")


Enter your name: Gurleen
Enter your age: 19
Hello Gurleen, you are 19 years old!


In [2]:
num = int(input("Enter a number: "))

print("Using for loop:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

print("\nUsing while loop:")
i = 1
while i <= 10:
    print(f"{num} x {i} = {num * i}")
    i += 1


Enter a number: 2
Using for loop:
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

Using while loop:
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [3]:
students = {"Aman": 85, "Riya": 92, "Kabir": 78}
top_student = max(students, key=students.get)
print(f"Top student: {top_student} ({students[top_student]} marks)")


Top student: Riya (92 marks)


In [4]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

primes = [str(i) for i in range(1, 101) if is_prime(i)]

with open("primes.txt", "w") as f:
    f.write("\n".join(primes))


In [5]:
is_prime(8)

False

In [6]:
is_prime(7)

True

In [7]:
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def average(self):
        return sum(self.marks) / len(self.marks)

s1 = Student("Aman", [85, 90, 80])
print(f"{s1.name}'s average: {s1.average()}")


Aman's average: 85.0


In [8]:
from abc import ABC, abstractmethod
import math

class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

class Rectangle(Shape):
    def __init__(self, l, w):
        self.l = l
        self.w = w
    def area(self):
        return self.l * self.w

class Circle(Shape):
    def __init__(self, r):
        self.r = r
    def area(self):
        return math.pi * self.r ** 2

r = Rectangle(5, 3)
c = Circle(4)
print("Rectangle area:", r.area())
print("Circle area:", round(c.area(), 2))


Rectangle area: 15
Circle area: 50.27


In [9]:
import numpy as np

# Task 1
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)
print("Shape:", matrix.shape, "Size:", matrix.size, "Dimensions:", matrix.ndim)

# Task 2
data = np.random.normal(0, 1, 100)
print("Mean:", np.mean(data), "Std Dev:", np.std(data))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3) Size: 9 Dimensions: 2
Mean: 0.02560047944431604 Std Dev: 1.1071656944030492
